-- Tabela: bling_pedidos_vendas
-- Pedidos de venda recebidos via webhook do Bling (order.*).
--
-- Campos estruturados extraídos do payload:
--   bling_id, numero, numero_loja, data, data_saida, data_prevista
--   total_produtos, total
--   situacao_id, situacao_valor
--   contato_id, contato_nome, contato_tipo_pessoa, contato_documento
--   loja_id, vendedor_id, observacoes, numero_pedido_compra
--
-- Campos JSONB (arrays variáveis):
--   itens, parcelas, transporte
--
-- payload_completo: JSON bruto completo para casos não mapeados
--
-- RLS: SELECT para admin e gerente; INSERT pelo service_role
--
-- CREATE TABLE bling_pedidos_vendas (
--   id                    UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
--   bling_evento_id       UUID        REFERENCES bling_eventos(id),
--   bling_id              BIGINT      NOT NULL,
--   acao                  VARCHAR(20) NOT NULL,
--   numero                VARCHAR(50),
--   numero_loja           VARCHAR(100),
--   data                  DATE,
--   data_saida            DATE,
--   data_prevista         DATE,
--   total_produtos        NUMERIC(15,2),
--   total                 NUMERIC(15,2),
--   situacao_id           INTEGER,
--   situacao_valor        VARCHAR(100),
--   contato_id            BIGINT,
--   contato_nome          VARCHAR(255),
--   contato_tipo_pessoa   CHAR(1),
--   contato_documento     VARCHAR(30),
--   loja_id               INTEGER,
--   vendedor_id           INTEGER,
--   observacoes           TEXT,
--   numero_pedido_compra  VARCHAR(100),
--   itens                 JSONB,
--   parcelas              JSONB,
--   transporte            JSONB,
--   payload_completo      JSONB       NOT NULL,
--   created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );
