-- OBSOLETO: A modelagem de Notas Fiscais (NFe e NFC-e) foi unificada de forma centralizada e profissional.
-- Todos os dados de notas fiscais, tanto do webhook quanto da API, agora residem nas tabelas:
--   1. public.nfe (contém o campo tipo_nota que diferencia 'NFe' e 'NFCe')
--   2. public.nfe_itens
--   3. public.nfe_parcelas
--
-- Consulte o arquivo schemas/bling_notas_fiscais.sql para a definição oficial destas tabelas.
